### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Newexplorer** [john-orr/renamer.vim#10]
"Dir contains 125 writeable files, but there are 124 listed in buffer.  These numbers should be equal"
What is going on here, and how can it be fixed?

**Comment by qpkorr** [comment]
The most common reason is you've deleted a line in the buffer so there's no longer a one to one correspondence between files in the directory listing and desired filenames - and the plugin doesn't try to guess which name goes with which file. But if you haven't deleted a line.... Is there a filename missing from the buffer that appears in  the directory - in which case, what's unusual  about that file?

**Comment by Newexplorer** [comment]
I have tried to figure it out myself, but I have been unable to. I think I have deleted a file.

But how can I determine which file is causing the problem? In other words, how can I compare the dir with the buffer?

**Comment by Newexplorer** [comment]
I found the solution. One of the files started with this: #. Once removed, everything was okay.
