### ISSUE TITLE
Changing file name case does not work (Windows)

### ISSUE THREAD

**Issue by Snaptags** [john-orr/renamer.vim#2]
I try to rename Files using Windows 8.1, e.g. „i am a file.txt“ to „I am a File.txt“,
but vim-renamer does not change the file names, it displays the OLD name after entering :Ren instead.

It does not even try to rename the file. I removed the actual renaming code in line 593 to verify this.

Unfortunately I did not find any code skipping files when only the casing has been changed…
(If I add or delete any characters, renaming does work as expected)

Any ideas?

**Comment by Snaptags** [comment]
Found it! Similar to JavaScript the == operator in vim script is NOT to be used ever, because you cannot rely on the result. In vim script == depends on the user setting of ignorecase :-(

**Comment by qpkorr** [comment]
Thank you - nice catch.  I'll pull your fix as soon as I can work out how! (I'm quite the novice on github)

**Comment by qpkorr** [comment]
Done I hope - thanks again for your help!
