### ISSUE TITLE
No license for this repo

### ISSUE THREAD

**Issue by draffensperger** [john-orr/renamer.vim#9]
Could you please add a license to this repo (e.g. MIT or Vim license)?

Not having a license can prevent people who have corporate policies around only using licensed software from being able to use this great plugin.

**Comment by qpkorr** [comment]
Don't suppose you'd like to add a pull request? :)  The Vim License seems appropriate to me...

**Comment by sgryjp** [comment]
Hi @qpkorr, do you mind if I suggest to apply MIT instead of Vim License? I can make a PR if you are okay with MIT.

For me, [Vim License](https://github.com/vim/vim/blob/master/runtime/doc/uganda.txt#L24) is too Vim specific and is hard to "translate" for vim-renamer.

**Comment by qpkorr** [comment]
On the off chance you still care... by all means make a PR with an MIT licence...

**Comment by sgryjp** [comment]
Thank you for responding! I sent a PR #13 some minutes ago.

**Comment by qpkorr** [comment]
Thanks very much! Looks good to me, merged and closed!
